
export const SPELLS_300: Record<string, { level: string, desc: string }> = {
  // Truques (Nível 0)
  "Amizade": { level: "Truque", desc: "Pessoal | Nenhum | Dá vantagem em testes de Carisma contra uma criatura." },
  "Ataque Certeiro": { level: "Truque", desc: "9m | Vantagem | Dá vantagem no seu próximo ataque contra o alvo." },
  "Bordão Místico": { level: "Truque", desc: "Pessoal | 1d8/1d10 Contundente | Transforma um cajado em uma arma mágica." },
  "Chama Sagrada": { level: "Truque", desc: "18m | 1d8 Radiante | Desce uma chama divina que ignora cobertura." },
  "Chicote de Espinhos": { level: "Truque", desc: "9m | 1d6 Perfurante | Puxa o alvo 3m para perto de você." },
  "Consertar": { level: "Truque", desc: "Toque | Nenhum | Repara um único quebro ou rasgo em um objeto." },
  "Criar Chamas": { level: "Truque", desc: "Pessoal/9m | 1d8 Fogo | Cria uma chama na mão que ilumina ou pode ser arremessada." },
  "Estilhaço de Gelo": { level: "Truque", desc: "18m | 1d8 Frio | Causa dano e reduz o deslocamento do alvo em 3m." },
  "Globos de Luz": { level: "Truque", desc: "36m | Nenhum | Cria até quatro luzes flutuantes." },
  "Ilusão Menor": { level: "Truque", desc: "9m | Nenhum | Cria um som ou imagem ilusória simples." },
  "Lufada de Vento": { level: "Truque", desc: "9m | Nenhum | Empurra criaturas ou objetos pequenos." },
  "Luz": { level: "Truque", desc: "Toque | Nenhum | Faz um objeto brilhar como uma tocha." },
  "Mãos Mágicas": { level: "Truque", desc: "9m | Nenhum | Cria uma mão espectral para manipular objetos à distância." },
  "Mensagem": { level: "Truque", desc: "36m | Nenhum | Sussurra uma mensagem que só o alvo ouve e pode responder." },
  "Moldar Água": { level: "Truque", desc: "9m | Nenhum | Move, muda a cor ou congela água." },
  "Moldar Terra": { level: "Truque", desc: "9m | Nenhum | Escava ou altera a terra em um espaço de 1,5m." },
  "Orientação": { level: "Truque", desc: "Toque | +1d4 (Teste) | Dá bônus em um teste de habilidade." },
  "Prestidigitação": { level: "Truque", desc: "3m | Nenhum | Truques mágicos inofensivos (limpar, sujar, acender)." },
  "Proteção contra Lâminas": { level: "Truque", desc: "Pessoal | Resistência | Resistência a dano contundente, cortante e perfurante." },
  "Rajada de Fogo": { level: "Truque", desc: "36m | 1d10 Fogo | Arremessa um dardo de chamas." },
  "Rajada de Veneno": { level: "Truque", desc: "3m | 1d12 Veneno | Projeta um gás tóxico na criatura." },
  "Rajada Mística": { level: "Truque", desc: "36m | 1d10 Energia | O clássico feixe de energia estalante dos Bruxos." },
  "Resistência": { level: "Truque", desc: "Toque | +1d4 (Resistência) | Dá bônus em um teste de resistência." },
  "Sinos dos Mortos": { level: "Truque", desc: "18m | 1d8/1d12 Necrótico | Causa mais dano se o alvo já estiver ferido." },
  "Taumaturgia": { level: "Truque", desc: "9m | Nenhum | Efeitos sobrenaturais menores (voz estrondosa, tremores)." },
  "Toque Arrepiante": { level: "Truque", desc: "36m | 1d8 Necrótico | Impede o alvo de recuperar pontos de vida." },
  "Toque Chocante": { level: "Truque", desc: "Toque | 1d8 Elétrico | Causa dano e impede o alvo de usar reações." },
  "Zombaria Viciosa": { level: "Truque", desc: "18m | 1d4 Psíquico | Insulta o alvo, causando dano e desvantagem no ataque." },
  "Palavra de Resplendor": { level: "Truque", desc: "1,5m | 1d6 Radiante | Causa dano a criaturas ao seu redor." },

  // Magias de Nível 1
  "Alarme": { level: "1º Nível", desc: "9m | Nenhum | Cria uma ala que avisa se alguém entrar." },
  "Amizade Animal": { level: "1º Nível", desc: "9m | Nenhum | Convence uma besta de que você não é uma ameaça." },
  "Área Escorregadia": { level: "1º Nível", desc: "18m | Derruba | Cobre o chão de graxa mágica, derrubando criaturas." },
  "Armadura Arcana": { level: "1º Nível", desc: "Toque | CA 13+Des | Dá proteção mágica para quem não usa armadura." },
  "Armadura de Agathys": { level: "1º Nível", desc: "Pessoal | 5 PV / 5 Frio | Armadura de gelo que fere quem te ataca corpo-a-corpo." },
  "Bênção": { level: "1º Nível", desc: "9m | +1d4 | Abençoa 3 criaturas com bônus em ataques e resistências." },
  "Bom Fruto": { level: "1º Nível", desc: "Toque | Cura 1 PV | Cria 10 frutos que curam e nutrem por um dia." },
  "Braços de Hadar": { level: "1º Nível", desc: "Pessoal | 2d6 Necrótico | Tentáculos sombrios atacam todos ao seu redor." },
  "Comando": { level: "1º Nível", desc: "18m | Efeito | Força o alvo a obedecer a uma ordem de uma palavra." },
  "Compreender Idiomas": { level: "1º Nível", desc: "Pessoal | Nenhum | Permite entender qualquer idioma falado ou escrito." },
  "Curar Ferimentos": { level: "1º Nível", desc: "Toque | 1d8 + Mod | Cura mágica por imposição de mãos." },
  "Destruição Colérica": { level: "1º Nível", desc: "Pessoal | 1d6 Psíquico | O próximo ataque corpo-a-corpo amedronta o alvo." },
  "Destruição Trovejante": { level: "1º Nível", desc: "Pessoal | 2d6 Trovejante | O próximo ataque empurra e derruba o alvo." },
  "Detectar Magia": { level: "1º Nível", desc: "Pessoal | Nenhum | Sente auras mágicas ao seu redor." },
  "Detectar Veneno": { level: "1º Nível", desc: "Pessoal | Nenhum | Localiza venenos e doenças em até 9m." },
  "Disfarçar-se": { level: "1º Nível", desc: "Pessoal | Ilusão | Muda sua aparência magicamente." },
  "Duelo Compelido": { level: "1º Nível", desc: "9m | Efeito | Força uma criatura a focar seus ataques em você." },
  "Escudo Arcano": { level: "1º Nível", desc: "Pessoal | +5 CA | Bloqueia ataques e Mísseis Mágicos." },
  "Escudo da Fé": { level: "1º Nível", desc: "18m | +2 CA | Um campo cintilante que protege uma criatura." },
  "Enfeitiçar Pessoa": { level: "1º Nível", desc: "9m | Enfeitiçado | Faz um humanoide enxergar você como um amigo." },
  "Falar com Animais": { level: "1º Nível", desc: "Pessoal | Nenhum | Permite comunicação com bestas." },
  "Falsa Vida": { level: "1º Nível", desc: "Pessoal | 1d4+4 PV Temp | Concede vitalidade necromântica temporária." },
  "Fogo das Fadas": { level: "1º Nível", desc: "18m | Vantagem | Contorna alvos com luz, impedindo invisibilidade." },
  "Golpe Certeiro": { level: "1º Nível", desc: "18m | +1d6 | Próximo ataque ignora meia-cobertura." },
  "Heroísmo": { level: "1º Nível", desc: "Toque | Imune a Medo | Torna alvo imune a medo e dá PV temporários." },
  "Identificar": { level: "1º Nível", desc: "Toque | Nenhum | Descobre as propriedades de um item mágico." },
  "Infligir Ferimentos": { level: "1º Nível", desc: "Toque | 3d10 Necrótico | Energia sombria que apodrece a carne do alvo." },
  "Leque Cromático": { level: "1º Nível", desc: "4,5m | Cega | Cegueira em área baseada nos PVs das criaturas." },
  "Mãos Flamejantes": { level: "1º Nível", desc: "4,5m | 3d6 Fogo | Um jato de chamas sai da ponta dos seus dedos." },
  "Marca do Caçador": { level: "1º Nível", desc: "27m | 1d6 | Marca um alvo para causar dano extra." },
  "Míssil Mágico": { level: "1º Nível", desc: "36m | 3x 1d4+1 | Três dardos mágicos que nunca erram o alvo." },
  "Névoa Obscurecente": { level: "1º Nível", desc: "36m | Cega | Cria uma densa nuvem de neblina." },
  "Onda Trovejante": { level: "1º Nível", desc: "4,5m | 2d8 Trovejante | Uma onda de som que empurra as criaturas." },
  "Orbe Cromático": { level: "1º Nível", desc: "27m | 3d8 Variável | Dispara uma esfera de energia elementar." },
  "Palavra Curativa": { level: "1º Nível", desc: "18m | 1d4 + Mod | Cura mágica rápida à distância." },
  "Passos Longos": { level: "1º Nível", desc: "Toque | +3m Desloc. | Aumenta a velocidade de movimento do alvo." },
  "Perdição": { level: "1º Nível", desc: "9m | -1d4 | Amaldiçoa 3 criaturas, prejudicando rolagens." },
  "Queda Suave": { level: "1º Nível", desc: "18m | Previne dano | Retarda a queda de até 5 criaturas." },
  "Raio Guiador": { level: "1º Nível", desc: "36m | 4d6 Radiante | Dá vantagem no próximo ataque de um aliado." },
  "Raio Adoecente": { level: "1º Nível", desc: "18m | 2d8 Necrótico | Causa dano e deixa o alvo envenenado." },
  "Recuo Acelerado": { level: "1º Nível", desc: "Pessoal | Disparada | Permite usar a ação Disparada como ação bônus." },
  "Salto": { level: "1º Nível", desc: "Toque | Triplica salto | Aumenta drasticamente a distância de pulo." },
  "Santuário": { level: "1º Nível", desc: "9m | Proteção | Inimigos precisam de teste para atacar o alvo." },
  "Sono": { level: "1º Nível", desc: "27m | Inconsciente | Coloca criaturas para dormir com base nos PVs." },
  "Vitalidade Falsa": { level: "1º Nível", desc: "Pessoal | PV Temp | Garante pontos de vida temporários." },

  // Magias de Nível 2
  "Acalmar Emoções": { level: "2º Nível", desc: "18m | Nenhum | Suprime medo, encantamento ou hostilidade." },
  "Acesso de Raiva": { level: "2º Nível", desc: "18m | Vantagem/Desvant. | Enche as criaturas de raiva cega." },
  "Alterar-se": { level: "2º Nível", desc: "Pessoal | Físico | Muda seu corpo (guelras, armas naturais)." },
  "Arma Espiritual": { level: "2º Nível", desc: "18m | 1d8 + Mod | Invoca arma flutuante que ataca (ação bônus)." },
  "Arma Mágica": { level: "2º Nível", desc: "Toque | +1 Atq/Dano | Torna arma não mágica em mágica temporariamente." },
  "Arrombar": { level: "2º Nível", desc: "18m | Nenhum | Abre trancas, portas e algemas." },
  "Aumentar/Reduzir": { level: "2º Nível", desc: "9m | Muda tamanho | Dobra ou reduz tamanho de criatura/objeto." },
  "Aviso": { level: "2º Nível", desc: "9m | Nenhum | Cria alarme mental ao detectar perigo." },
  "Cegueira/Surdez": { level: "2º Nível", desc: "9m | Cego/Surdo | Priva o alvo da visão ou audição." },
  "Chama Contínua": { level: "2º Nível", desc: "Toque | Nenhum | Cria uma chama permanente sem calor." },
  "Coroa da Loucura": { level: "2º Nível", desc: "36m | Encantamento | Força alvo a atacar seus próprios aliados." },
  "Crescer Espinhos": { level: "2º Nível", desc: "45m | 2d4 Perfurante | Chão vira espinhos perigosos." },
  "Deslocamento": { level: "2º Nível", desc: "Pessoal | Desvantagem | Faz você parecer estar em outro lugar." },
  "Detectar Pensam.": { level: "2º Nível", desc: "Pessoal | Nenhum | Lê pensamentos superficiais das criaturas." },
  "Esfera Flamejante": { level: "2º Nível", desc: "18m | 2d6 Fogo | Invoca bola de fogo rolante que você controla." },
  "Espírito Curativo": { level: "2º Nível", desc: "18m | 1d6 Cura | Invoca um espírito que cura quem passa por ele." },
  "Esquentar Metal": { level: "2º Nível", desc: "18m | 2d8 Fogo | Deixa armaduras de metal em brasa." },
  "Escuridão": { level: "2º Nível", desc: "18m | Cega | Cria esfera de escuridão mágica intransponível." },
  "Força Fantasma": { level: "2º Nível", desc: "18m | 1d6 Psíquico | Ilusão na mente do alvo que ele acredita ser real." },
  "Invisibilidade": { level: "2º Nível", desc: "Toque | Invisível | Torna alvo invisível até que ataque ou conjure." },
  "Levitar": { level: "2º Nível", desc: "18m | Nenhum | Faz criatura ou objeto flutuar no ar." },
  "Mensag. Animal": { level: "2º Nível", desc: "9m | Nenhum | Envia animal minúsculo para entregar mensagem." },
  "Montaria Fantasma": { level: "2º Nível", desc: "9m | Montaria | Invoca um corcel rápido e quase irreal." },
  "Nuvem de Adagas": { level: "2º Nível", desc: "18m | 4d4 Cortante | Cubo cheio de adagas voadoras." },
  "Oração Curativa": { level: "2º Nível", desc: "9m | 2d8 + Mod | Cura até 6 criaturas fora de combate." },
  "Passar sem Rastros": { level: "2º Nível", desc: "Pessoal | +10 Furtividade | Oculta rastros e dá bônus para esconder em grupo." },
  "Passo Nebuloso": { level: "2º Nível", desc: "Pessoal | Teletransporte | Teletransporta você 9m como ação bônus." },
  "Raio Ardente": { level: "2º Nível", desc: "36m | 3x 2d6 Fogo | Dispara três raios de fogo em alvos." },
  "Raio do Enfraq.": { level: "2º Nível", desc: "18m | Debuff | Reduz pela metade dano físico causado pelo alvo." },
  "Reflexos": { level: "2º Nível", desc: "Pessoal | Ilusão | Cria 3 cópias suas que absorvem ataques." },
  "Restauração Menor": { level: "2º Nível", desc: "Toque | Cura Condição | Remove cegueira, surdez, paralisia ou veneno." },
  "Seta Ácida": { level: "2º Nível", desc: "27m | 4d4 + 2d4 Ácido | Seta ácida com dano contínuo no próximo turno." },
  "Silêncio": { level: "2º Nível", desc: "36m | Silêncio | Cria esfera onde nenhum som é emitido." },
  "Sugestão": { level: "2º Nível", desc: "9m | Encantamento | Sugere ação que o alvo é forçado a seguir." },
  "Teia": { level: "2º Nível", desc: "18m | Impedido | Preenche área com teias grudentas." },
  "Truque de Corda": { level: "2º Nível", desc: "Toque | Esconderijo | Espaço extradimensional no topo de uma corda." },
  "Vento Protetor": { level: "2º Nível", desc: "Pessoal | Defesa | Afasta gases e dificulta ataques à distância." },
  "Ver o Invisível": { level: "2º Nível", desc: "Pessoal | Visão | Permite ver criaturas invisíveis ou no Plano Etéreo." },
  "Vínculo Protetor": { level: "2º Nível", desc: "Toque | +1 CA/Res | Você e um aliado dividem todo o dano recebido." },

  // Magias de Nível 3
  "Andar na Água": { level: "3º Nível", desc: "9m | Nenhum | Permite caminhar sobre líquidos." },
  "Dissipar Magia": { level: "3º Nível", desc: "36m | Fim de Efeito | Encerra efeitos mágicos em alvos ou áreas." },
  "Animar Mortos": { level: "3º Nível", desc: "3m | Invoca | Levanta um esqueleto ou zumbi." },
  "Aura de Vitalidade": { level: "3º Nível", desc: "Pessoal | 2d6 Cura | Cura aliados próximos como ação bônus." },
  "Bola de Fogo": { level: "3º Nível", desc: "45m | 8d6 Fogo | A clássica e devastadora explosão em área." },
  "Círculo Mágico": { level: "3º Nível", desc: "3m | Proteção | Prende ou afasta criaturas extraplanares." },
  "Clarividência": { level: "3º Nível", desc: "1,5 km | Visão/Audição | Sensor invisível para espionar local distante." },
  "Contra-mágica": { level: "3º Nível", desc: "18m | Interrupção | Tenta cancelar magia de outra criatura." },
  "Crescimento Plantas": { level: "3º Nível", desc: "45m | Terreno Difícil | Transforma flora local em matagal impenetrável." },
  "Dificultar Detecção": { level: "3º Nível", desc: "Toque | Furtividade | Esconde alvo de magias de adivinhação." },
  "Espíritos Guardiões": { level: "3º Nível", desc: "Pessoal | 3d8 Radiante | Espíritos ferem inimigos e reduzem velocidade." },
  "Falar com os Mortos": { level: "3º Nível", desc: "3m | Informação | Permite fazer 5 perguntas a um cadáver." },
  "Fingir Morte": { level: "3º Nível", desc: "Toque | Catalepsia | Coloca aliado em estado idêntico à morte." },
  "Fome de Hadar": { level: "3º Nível", desc: "45m | Frio + Ácido | Abre fenda escura para o vazio espacial." },
  "Forma Gasosa": { level: "3º Nível", desc: "Toque | Transmutação | Transforma criatura em nuvem de gás imaterial." },
  "Pequena Cabana": { level: "3º Nível", desc: "Pessoal | Abrigo | Cria domo impenetrável para descanso seguro." },
  "Glifo de Guarda": { level: "3º Nível", desc: "Toque | Armadilha | Runa explosiva que detona sob condições." },
  "Idiomas": { level: "3º Nível", desc: "Toque | Comunicação | Permite ao alvo entender e falar todos idiomas." },
  "Lentidão": { level: "3º Nível", desc: "36m | Debuff | Desacelera até 6 inimigos (movimento, CA)." },
  "Luz do Dia": { level: "3º Nível", desc: "18m | Luz | Cria esfera de luz tão forte quanto o sol." },
  "Medo": { level: "3º Nível", desc: "9m | Fuga | Ilusão que faz inimigos largarem armas e fugirem." },
  "Mesclar-se a Rochas": { level: "3º Nível", desc: "Toque | Esconderijo | Permite entrar em uma superfície de pedra sólida." },
  "Névoa Fétida": { level: "3º Nível", desc: "27m | Náusea | Nuvem de gás nojento que faz perder ações." },
  "Padrão Hipnótico": { level: "3º Nível", desc: "36m | Encantamento | Caleidoscópio de cores que paralisa quem olhar." },
  "Palavra Cura em Massa": { level: "3º Nível", desc: "18m | Cura | Cura até 6 aliados simultaneamente (ação bônus)." },
  "Passo Trovejante": { level: "3º Nível", desc: "27m | 3d10 Trovejante | Teletransporte com explosão sonora para trás." },
  "Piscar": { level: "3º Nível", desc: "Pessoal | Defesa | Transporta para Plano Etéreo entre turnos." },
  "Proteção contra Energia": { level: "3º Nível", desc: "Toque | Resistência | Dá resistência a um elemento escolhido." },
  "Relâmpago": { level: "3º Nível", desc: "Pessoal | 8d6 Elétrico | Dispara uma linha reta de pura eletricidade." },
  "Remover Maldição": { level: "3º Nível", desc: "Toque | Cura | Quebra vínculo de itens e remove maldições." },
  "Reviver": { level: "3º Nível", desc: "Toque | Ressurreição | Traz de volta criatura morta no último minuto." },
  "Tempestade de Neve": { level: "3º Nível", desc: "45m | Cegueira | Gelo escorregadio e neve cegante em área." },
  "Toque Vampírico": { level: "3º Nível", desc: "Pessoal | 3d6 Necrótico | Drena vida do alvo, curando metade do dano." },
  "Velocidade": { level: "3º Nível", desc: "9m | +2 CA/Ação | Dá ataque extra, CA e dobro de movimento." },

  // Magias de Nível 4
  "Assassino Fantasmagórico": { level: "4º Nível", desc: "36m | 4d10 Psíquico | Amedronta o alvo com seus piores pesadelos." },
  "Aura de Pureza": { level: "4º Nível", desc: "Pessoal | Defesa | Protege aliados próximos contra doenças e condições." },
  "Aura de Vida": { level: "4º Nível", desc: "Pessoal | Cura | Dá resistência a dano necrótico e revive aliados." },
  "Banimento": { level: "4º Nível", desc: "18m | Exílio | Envia criatura para outro plano temporariamente." },
  "Cão Fiel de Mordenkainen": { level: "4º Nível", desc: "9m | 4d8 Perfurante | Invoca cão invisível que morde invasores." },
  "Confusão": { level: "4º Nível", desc: "27m | Debuff | Faz criaturas em área agirem aleatoriamente." },
  "Conjurar Seres da Floresta": { level: "4º Nível", desc: "18m | Invocação | Traz fadas para lutar por você." },
  "Conjurar Elementais Menores": { level: "4º Nível", desc: "27m | Invocação | Invoca até 8 elementais fracos." },
  "Controlar a Água": { level: "4º Nível", desc: "90m | Terreno | Cria inundações, divide mares ou forma redemoinhos." },
  "Destruição Estonteante": { level: "4º Nível", desc: "Pessoal | 4d6 Psíquico | Ataque dá dano e atordoa inimigo." },
  "Esfera Resiliente de Otiluke": { level: "4º Nível", desc: "9m | Prisão | Prende alvo em bolha mágica indestrutível." },
  "Espaço Secreto": { level: "4º Nível", desc: "9m | Esconderijo | Esconde área inteira de observadores externos." },
  "Fabricar": { level: "4º Nível", desc: "36m | Transmutação | Transforma matéria-prima bruta em produto acabado." },
  "Invisibilidade Maior": { level: "4º Nível", desc: "Toque | Invisível | Não acaba se o alvo atacar ou conjurar." },
  "Localizar Criatura": { level: "4º Nível", desc: "Pessoal | Busca | Sente direção da criatura específica mais próxima." },
  "Maldição Elemental": { level: "4º Nível", desc: "27m | Vulnerabilidade | Alvo perde resistência e sofre dano elemental extra." },
  "Metamorfose": { level: "4º Nível", desc: "18m | Transformation | Transforma alvo completamente em uma besta." },
  "Moldar Rochas": { level: "4º Nível", desc: "Toque | Alteração | Molda um pedaço de pedra em qualquer formato." },
  "Muralha de Fogo": { level: "4º Nível", desc: "36m | 5d8 Fogo | Levanta parede ardente que queima quem passa." },
  "Olho Arcano": { level: "4º Nível", desc: "9m | Espionagem | Olho flutuante invisível para explorar áreas." },
  "Pele de Pedra": { level: "4º Nível", desc: "Toque | Resistência | Resistência a dano físico não mágico." },
  "Perdição (Secar)": { level: "4º Nível", desc: "9m | 8d8 Necrótico | Drena umidade do alvo, fatal para plantas." },
  "Porta Dimensional": { level: "4º Nível", desc: "150m | Teletransporte | Salto espacial para um ponto escolhido." },
  "Proteção contra a Morte": { level: "4º Nível", desc: "Toque | Sobrevivência | Impede alvo de cair a 0 PV na próxima vez." },
  "Santuário Particular": { level: "4º Nível", desc: "36m | Proteção | Protege área contra vidência e teletransporte." },
  "Tempestade de Gelo": { level: "4º Nível", desc: "90m | 2d8 Cont + 4d6 Frio | Chuva violenta de granizo congelante." },
  "Tentáculos Negros de Evard": { level: "4º Nível", desc: "27m | 3d6 Contundente | Tentáculos agarram e esmagam criaturas na área." },
  "Terreno Alucinatório": { level: "4º Nível", desc: "90m | Ilusão | Faz ambiente natural parecer outra coisa." },
  "Vinha Esmagadora": { level: "4º Nível", desc: "9m | Invoca Planta | Chicote de vinha que agarra e puxa criaturas." },

  // Magias de Nível 5
  "Amigos Inseparáveis": { level: "5º Nível", desc: "Pessoal | Comunicação | Grupo conversa por telepatia a qualquer distância." },
  "Animar Objetos": { level: "5º Nível", desc: "36m | Invocação | Dá vida a até 10 objetos não-mágicos para lutar." },
  "Ataque Visual": { level: "5º Nível", desc: "Pessoal | 4d8 Psíquico | Olhar aterrorizante que causa dano." },
  "Aura de Sagacidade": { level: "5º Nível", desc: "Pessoal | Encantamento | Aliados ganham vantagem em testes mentais." },
  "Banimento (Círculo)": { level: "5º Nível", desc: "3m | Viagem | Conecta a um círculo de teletransporte permanente." },
  "Caminhar em Árvores": { level: "5º Nível", desc: "Pessoal | Viagem | Entra em uma árvore e sai em outra igual." },
  "Carapaça Antimagia": { level: "5º Nível", desc: "Pessoal | Barreira | Bloqueia magias de nível 5 ou menor ao redor." },
  "Comando em Massa": { level: "5º Nível", desc: "18m | Encantamento | Versão poderosa de Comando afetando vários alvos." },
  "Comunhão": { level: "5º Nível", desc: "Pessoal | Informação | Três perguntas \"sim/não\" para uma divindade." },
  "Comunhão com a Natureza": { level: "5º Nível", desc: "Pessoal | Informação | Conhecimento imediato sobre território ao redor." },
  "Cone de Frio": { level: "5º Nível", desc: "18m | 8d8 Frio | Lufada de vento absurdamente frio que congela." },
  "Conhecimento das Lendas": { level: "5º Nível", desc: "Pessoal | Informação | Revela mistérios sobre pessoa, local ou item." },
  "Conjurar Elementais": { level: "5º Nível", desc: "27m | Invocação | Invoca um Elemental Maior aliado." },
  "Criação": { level: "5º Nível", desc: "9m | Transmutação | Cria objetos de matéria da umbra temporariamente." },
  "Curar Ferimentos em Massa": { level: "5º Nível", desc: "18m | 3d8 + Mod | Cura em área para até 6 criaturas simultâneas." },
  "Despertar": { level: "5º Nível", desc: "Toque | Inteligência | Dá inteligência humana e fala a besta/árvore." },
  "Destruição Banidora": { level: "5º Nível", desc: "Pessoal | 5d10 Energia | Se alvo cair a <50 PV, é banido temporariamente." },
  "Dominação de Pessoa": { level: "5º Nível", desc: "18m | Controle | Assume total controle sobre ações de humanoide." },
  "Golpe Flamejante": { level: "5º Nível", desc: "18m | 4d6 Fogo/Rad | Pilar de fogo celestial desce dos céus." },
  "Imobilizar Monstro": { level: "5º Nível", desc: "27m | Paralisia | Paralisa qualquer tipo de criatura." },
  "Mão de Bigby": { level: "5º Nível", desc: "36m | 4d8 Contundente | Mão gigante de força que soca, esmaga ou defende." },
  "Muralha de Força": { level: "5º Nível", desc: "36m | Bloqueio | Parede ou domo invisível e indestrutível." },
  "Muralha de Pedra": { level: "5º Nível", desc: "36m | Barreira | Cria parede de pedra grossa e moldável." },
  "Névoa Mortal": { level: "5º Nível", desc: "36m | 5d8 Veneno | Gás pesado que mata tudo que respira na área." },
  "Passo das Sombras": { level: "5º Nível", desc: "90m | Deslocamento | Pula através de sombras conectadas." },
  "Praga de Insetos": { level: "5º Nível", desc: "90m | 4d10 Perfurante | Nuvem gigante de insetos agressivos." },
  "Reencarnação": { level: "5º Nível", desc: "Toque | Ressurreição | Revive, mas constrói corpo novo de raça aleatória." },
  "Restauração Maior": { level: "5º Nível", desc: "Toque | Cura Maior | Remove exaustão, maldições, petrificação." },
  "Similaridade (Geas)": { level: "5º Nível", desc: "18m | Coerção | Força alvo a seguir ordem por 30 dias sob dor." },
  "Sonho": { level: "5º Nível", desc: "Especial | Mensagem | Molda sonho para entregar mensagem ou pesadelo." },

  // Magias de Nível 6
  "Aliado Planar": { level: "6º Nível", desc: "18m | Invocação | Conjura ser divino em troca de barganha." },
  "Ataque Visual Maior": { level: "6º Nível", desc: "Pessoal | Dano/Debuff | Olhar causa desvantagem, medo e fraqueza." },
  "Banquete de Heróis": { level: "6º Nível", desc: "9m | Buff/Cura | Cura, imuniza contra veneno/medo e dá bônus." },
  "Barreira de Lâminas": { level: "6º Nível", desc: "27m | 6d10 Cortante | Parede giratória de espadas afiadas." },
  "Carne para Pedra": { level: "6º Nível", desc: "18m | Petrificação | Transforma alvo vivo em estátua de pedra." },
  "Círculo da Morte": { level: "6º Nível", desc: "45m | 8d6 Necrótico | Onda de decadência que devasta grandes áreas." },
  "Conjurar Fada": { level: "6º Nível", desc: "27m | Invocação | Invoca espírito feérico de alto poder." },
  "Corrente de Relâmpagos": { level: "6º Nível", desc: "45m | 10d8 Elétrico | Raio atinge alvo e salta para outros 3." },
  "Cura Plena": { level: "6º Nível", desc: "18m | 70 PV Fixo | Cura enorme quantidade de PV de uma só vez." },
  "Dança Irresistível de Otto": { level: "6º Nível", desc: "9m | Debuff | Força criatura a dançar descontroladamente." },
  "Desintegrar": { level: "6º Nível", desc: "18m | 10d6 + 40 | Reduz alvo a pó se PV cair a 0." },
  "Doença Plena (Harm)": { level: "6º Nível", desc: "18m | 14d6 Necrótico | Apodrecimento que reduz PV máximos do alvo." },
  "Encontrar o Caminho": { level: "6º Nível", desc: "Pessoal | Navegação | Mostra rota mais curta para local específico." },
  "Esfera Congelante de Otiluke": { level: "6º Nível", desc: "90m | 10d6 Frio | Globo congelante explosivo, pode ser atirado depois." },
  "Globo de Invulnerabilidade": { level: "6º Nível", desc: "Pessoal | Defesa | Anula magias de nível 5 ou menor de fora." },
  "Ilusão Programada": { level: "6º Nível", desc: "36m | Ilusão | Cena de ilusão complexa engatilhada por condição." },
  "Invocação Inst. de Drawmij": { level: "6º Nível", desc: "Toque | Invocação | Marca objeto e invoca-o à mão de qualquer lugar." },
  "Magia Contingente": { level: "6º Nível", desc: "Pessoal | Preparação | Armazena magia ativada por condição pré-estabelecida." },
  "Mover Terra": { level: "6º Nível", desc: "36m | Alteração | Move montes, elevações ou cava fossos gigantescos." },
  "Muralha de Gelo": { level: "6º Nível", desc: "36m | 10d6 Frio | Barreira glacial; ao quebrar deixa ar cortante." },
  "Muralha de Espinhos": { level: "6º Nível", desc: "36m | 7d8 Perfurante | Espinhos grossos bloqueiam o caminho." },
  "Palavra de Recordação": { level: "6º Nível", desc: "Pessoal | Fuga | Teletransporte instantâneo para um santuário." },
  "Passo no Vento": { level: "6º Nível", desc: "Pessoal | Viagem | Permite viajar transformado em vento rápido." },
  "Portão Arcano": { level: "6º Nível", desc: "150m | Teletransporte | Cria dois portais interligados para travessia." },
  "Proibição": { level: "6º Nível", desc: "Toque | Proteção | Sela área imensa contra teletransporte e extraplanares." },
  "Raio Solar": { level: "6º Nível", desc: "Pessoal | 6d8 Radiante | Raios ofuscantes de pura luz a cada turno." },
  "Sugestão em Massa": { level: "6º Nível", desc: "18m | Encantamento | Dá ordens razoáveis para até 12 criaturas." },
  "Transporte Via Plantas": { level: "6º Nível", desc: "3m | Teletransporte | Viaja de uma árvore grande a outra no mundo." },
  "Truque de Mágica": { level: "6º Nível", desc: "Toque | Ilusão | Cria truques arcanos e ambientais altamente complexos." },
  "Visão da Verdade": { level: "6º Nível", desc: "Toque | Visão | Vê através de ilusão, invisibilidade e disfarce." },

  // Magias de Nível 7
  "Bola de Fogo Controlável": { level: "7º Nível", desc: "45m | 12d6 Fogo | Esfera que explode ou acumula poder no ar." },
  "Cúpula Cintilante": { level: "7º Nível", desc: "Pessoal | Proteção | Redoma que pune inimigos invasores com dano elétrico." },
  "Dedo da Morte": { level: "7º Nível", desc: "18m | 7d8 + 30 | Fatal; ergue alvo como zumbi se matar." },
  "Espada de Mordenkainen": { level: "7º Nível", desc: "18m | 3d10 Energia | Evoca espada de força controlada pelo pensamento." },
  "Eterealidade": { level: "7º Nível", desc: "Pessoal | Viagem Planar | Leva grupo ao Plano Etéreo para atravessar paredes." },
  "Forma Etérea": { level: "7º Nível", desc: "Pessoal | Viagem | Anda invisível e intangível pelo plano material." },
  "Ilusão de Puxão": { level: "7º Nível", desc: "36m | Encantamento | Atrai alvos hipnoticamente para o centro de uma área." },
  "Inversão da Gravidade": { level: "7º Nível", desc: "30m | Efeito | Inimigos \"caem\" em direção ao céu." },
  "Jaula de Força": { level: "7º Nível", desc: "30m | Prisão | Prisão indestrutível que bloqueia até teletransporte." },
  "Lufada de Vento Divina": { level: "7º Nível", desc: "36m | Controle | Tufão sagrado ou arcano gigantesco." },
  "Magnificência de Morden.": { level: "7º Nível", desc: "90m | Luxo | Mansão extradimensional com servos invisíveis." },
  "Miragem": { level: "7º Nível", desc: "Visão | Ilusão Extrema | Altera a percepção visual/tátil de 1,5 km do terreno." },
  "Palavra Divina": { level: "7º Nível", desc: "9m | Dano/Efeito | Som que expulsa extraplanares e mata alvos fracos." },
  "Prisão de Gelo": { level: "7º Nível", desc: "18m | 10d6 Frio | Congela criatura viva numa tumba impenetrável." },
  "Projeção Holográfica": { level: "7º Nível", desc: "Pessoal | Ilusão | Simulacro que conjura magias em seu lugar." },
  "Raio Prismático": { level: "7º Nível", desc: "18m | Variado | Cone de 7 luzes mortais com efeitos aleatórios." },
  "Ressurreição": { level: "7º Nível", desc: "Toque | Ressurreição | Revive alguém morto há menos de 1 século." },
  "Símbolo": { level: "7º Nível", desc: "Toque | Armadilha | Runa mortífera engatilhada (dor, sono, morte)." },
  "Teletransporte": { level: "7º Nível", desc: "3m | Viagem | Salto para qualquer lugar do mesmo mundo." },
  "Viagem Planar": { level: "7º Nível", desc: "Toque | Fuga/Viagem | Leva grupo a outro plano ou bane inimigo hostil." },

  // Magias de Nível 8
  "Aura Sagrada": { level: "8º Nível", desc: "Pessoal | Proteção | Vantagem aliados, desvantagem inimigos, cega zumbis." },
  "Campo Antimagia": { level: "8º Nível", desc: "Pessoal | Bloqueio | Raio absoluto onde NENHUMA magia funciona." },
  "Clone": { level: "8º Nível", desc: "Toque | Imortalidade | Cultiva corpo cópia. Se morrer, acorda no clone." },
  "Controlar o Clima": { level: "8º Nível", desc: "Pessoal | Clima | Muda condições atmosféricas em área imensa." },
  "Dominar Monstro": { level: "8º Nível", desc: "18m | Controle Total | Controle mental definitivo sobre qualquer criatura." },
  "Enfraquecer o Intelecto": { level: "8º Nível", desc: "45m | 4d6 Psíquico | Zera Inteligência e Carisma, impedindo fala/magia." },
  "Escudo Mental": { level: "8º Nível", desc: "Toque | Defesa | Imunidade a dano psíquico, divinação e charme." },
  "Explosão Solar": { level: "8º Nível", desc: "45m | 12d6 Radiante | Sol artificial que cega e desintegra mortos-vivos." },
  "Limpar a Mente": { level: "8º Nível", desc: "Toque | Buff | Cura imediatamente charme e loucura." },
  "Labirinto": { level: "8º Nível", desc: "18m | Banimento | Prende alvo em dimensão-labirinto de minotauros." },
  "Nuvem Incendiária": { level: "8º Nível", desc: "45m | 10d8 Fogo | Fumaça de brasas que varre o campo incinerando." },
  "Palavra Atordoar": { level: "8º Nível", desc: "18m | Atordoamento | Alvos com 150 PV ou menos são atordoados sem teste." },
  "Poeira da Morte": { level: "8º Nível", desc: "36m | 10d10 Necrótico | Cone horrendo que corrói os alvos fisicamente." },
  "Telepatia": { level: "8º Nível", desc: "Ilimitado | Comunicação | Elo telepático eterno com criatura no mesmo plano." },
  "Terremoto": { level: "8º Nível", desc: "150m | Destruição | Despedaça castelos e abre fendas esmagadoras." },
  "Tsunami": { level: "8º Nível", desc: "Visão | Destruição | Parede d'água de 90m que esmaga construções." },
  "Afinidade Animal Maior": { level: "8º Nível", desc: "9m | Criação | Traz feras gigantes sob seu controle." },
  "Encarnação do Mal": { level: "8º Nível", desc: "Pessoal | Dano | Exala aura macabra que condena os inimigos." },
  "Raio Polar": { level: "8º Nível", desc: "36m | Frio Extremo | Rajadas que cristalizam instantaneamente." },
  "Luz Divina Extrema": { level: "8º Nível", desc: "Visão | Radiante | Feixes dos céus que expurgam alinhamento contrário." },

  // Magias de Nível 9
  "Aprisionamento": { level: "9º Nível", desc: "9m | Selamento | Enterra ou sela alvo perpetuamente em cristal." },
  "Sexto Sentido": { level: "9º Nível", desc: "Toque | Vantagem Absoluta | Vê o futuro por 8h; impenetrável em combate." },
  "Desejo": { level: "9º Nível", desc: "Pessoal | Tudo | Altera regras do universo, cópia feitiços." },
  "Chuva de Meteoros": { level: "9º Nível", desc: "1,5 km | 40d6 Misto | Chama 4 rochas cósmicas, devastando o campo." },
  "Palavra de Poder Curar": { level: "9º Nível", desc: "Toque | Cura Total | Recupera todos os PV e limpa condições do alvo." },
  "Palavra de Poder Matar": { level: "9º Nível", desc: "18m | Morte Instantânea | Com <100 PV, o alvo simplesmente morre na hora." },
  "Parar o Tempo": { level: "9º Nível", desc: "Pessoal | Tempo | Mundo inteiro congela por 1d4+1 turnos para você agir." },
  "Portal": { level: "9º Nível", desc: "18m | Viagem | Abre fenda interplanar e invoca seres específicos." },
  "Projeção Astral": { level: "9º Nível", desc: "Toque | Viagem Astral | Corpos dormem; grupo navega no Mar Astral." },
  "Ressurreição Verdadeira": { level: "9º Nível", desc: "Toque | Ress. Divina | Revive morto há até 200 anos sem precisar do corpo." },
  "Metamorfose Verdadeira": { level: "9º Nível", desc: "9m | Mudança Eterna | Transforma qualquer coisa em qualquer coisa pra sempre." },
  "Muralha Prismática": { level: "9º Nível", desc: "18m | Barreira Máxima | Muro de 7 camadas intransponíveis." },
  "Tempestade de Vingança": { level: "9º Nível", desc: "Visão | Apocalipse | Chuva de ácido, relâmpago e saraiva por minutos." },
  "Alterar Realidade": { level: "9º Nível", desc: "Especial | Modificação | Molda grandes escopos de mundo celestial." },
  "Julgamento de Fogo": { level: "9º Nível", desc: "45m | 30d6 Radiante | Explosão concentrada da ira de um panteão divino." },
  "Fenda Planar Múltipla": { level: "9º Nível", desc: "30m | Caos | Mistura 3 planos mortais no meio do combate." },
  "Invocação de Titãs": { level: "9º Nível", desc: "90m | Invocação Suprema | Puxa elementais anciões do caos primevo." },
  "Sinfonia da Ruína": { level: "9º Nível", desc: "18m | Dano/Debuff | Canção dilacerante; corta metade dos atributos." },
  "Aura dos Deuses": { level: "9º Nível", desc: "Pessoal | Invulnerabilidade | Imunidade a danos mundanos e mágicos inferiores." },
  "Eclipse de Sombras": { level: "9º Nível", desc: "Céu | Escuridão | Apaga o sol de uma área, espalhando pânico extremo." },
  "Réquiem Final": { level: "9º Nível", desc: "90m | Necromancia Max. | Ergue exército imediato de todos os corpos caídos." }
};
